export const sidebar = {
  statusCode: 200,
  code: 1,
  errorMessages: 'Success',
  data: [
    {
      id: 7,
      code: null,
      name: 'Cấu hình tham số',
      url: null,
      status: 1,
      lever: 1,
      parentId: null,
      parentName: null,
      partToRoot: '/7/',
      subMenuList: null,
    },
    {
      id: 1,
      code: 'QTHT',
      name: 'Quản trị hệ thống',
      url: '',
      status: 1,
      lever: 1,
      parentId: null,
      parentName: null,
      partToRoot: '/1/',
      subMenuList: [
        {
          id: 6,
          code: 'QLR',
          name: 'Quản lý nhóm người dùng',
          url: '',
          status: 1,
          lever: 2,
          parentId: 1,
          parentName: null,
          partToRoot: '/1/6',
          subMenuList: null,
        },
        {
          id: 2,
          code: 'QLND',
          name: 'Quản lý người dùng',
          url: '',
          status: 1,
          lever: 1,
          parentId: 1,
          parentName: null,
          partToRoot: '/1/2/',
          subMenuList: [
            {
              id: 9,
              code: 'QLND',
              name: 'Quản lý user',
              url: null,
              status: 1,
              lever: 1,
              parentId: 2,
              parentName: null,
              partToRoot: '/1/2/9',
              subMenuList: [
                {
                  id: 11,
                  code: 'TEST2',
                  name: 'TEST2',
                  url: null,
                  status: 1,
                  lever: 2,
                  parentId: 9,
                  parentName: null,
                  partToRoot: '/1/2/9/11',
                  subMenuList: [
                    {
                      id: 12,
                      code: 'TEST3',
                      name: 'TEST3',
                      url: null,
                      status: 1,
                      lever: 1,
                      parentId: 11,
                      parentName: null,
                      partToRoot: '/1/2/9/11/12',
                      subMenuList: [
                        {
                          id: 13,
                          code: 'TEST4',
                          name: 'TEST4',
                          url: null,
                          status: 1,
                          lever: 1,
                          parentId: 12,
                          parentName: null,
                          partToRoot: '/1/2/9/11/12/13',
                          subMenuList: null,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 4,
      code: 'EXPORT',
      name: 'Quản lý xuất file',
      url: '',
      status: 1,
      lever: 1,
      parentId: null,
      parentName: null,
      partToRoot: '/4/',
      subMenuList: [
        {
          id: 3,
          code: 'EP',
          name: 'Xuất file CSV',
          url: '',
          status: 1,
          lever: 1,
          parentId: 4,
          parentName: null,
          partToRoot: '/4/3/',
          subMenuList: [
            {
              id: 10,
              code: 'TEST1',
              name: 'TEST1',
              url: null,
              status: 1,
              lever: 2,
              parentId: 3,
              parentName: null,
              partToRoot: '/4/3/10',
              subMenuList: null,
            },
            {
              id: 5,
              code: 'EP_DATA',
              name: 'File Dump Data',
              url: '',
              status: 1,
              lever: 1,
              parentId: 3,
              parentName: null,
              partToRoot: '/4/3/5',
              subMenuList: [
                {
                  id: 8,
                  code: 'EP_DATA_SUB',
                  name: 'File Dump Data SIM',
                  url: null,
                  status: 1,
                  lever: 1,
                  parentId: 5,
                  parentName: null,
                  partToRoot: '/4/3/5/8',
                  subMenuList: null,
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
